language:
    - cpp
compiler:
    - clang
    - gcc
dist:
    - trusty
before_install:
    - sudo apt-get update -qq -y
    - sudo apt-get install -y gfortran
    - git clone https://github.com/xianyi/OpenBLAS
    - cd OpenBLAS
    - make
    - sudo make install
script:
    - make -C test
