language:
    - cpp
compiler:
    - clang
    - gcc
dist:
    - trusty
cache:
    directories:
    - ../OpenBLAS
before_install:
    - sudo apt-get update -qq -y
    - sudo apt-get install -y gfortran
    - git clone https://github.com/xianyi/OpenBLAS ../OpenBLAS || (cd ../OpenBLAS && git pull)
    - (cd ../OpenBLAS && make && make install)
script:
    - make LFLAGS="-I/opt/OpenBLAS/include -L/opt/OpenBLAS/lib" test
