language:
    - cpp
compiler:
    - clang
    - gcc
dist:
    - trusty
cache:
    directories:
    - cache
before_install:
    - sudo apt-get update -qq -y
    - sudo apt-get install -y gfortran
    - mkdir -p cache
    - git clone https://github.com/xianyi/OpenBLAS cache/openblas || true
    - cd cache/openblas
    - git pull
    - make && make PREFIX=/opt/OpenBLAS install
script:
    - make LFLAGS="-I/opt/OpenBLAS/include -L/opt/OpenBLAS/lib" test
